### PR TITLE
chore: update readme

### PR DESCRIPTION
**Pull request by derpierre65**
- i changed the HTML to markdown in the README.md and removed the center alignment to improve readability and accessibility for most people.
  - and it's so much easier to edit
  - I can center everything again if you want (without losing the markdown), but some sections are much easier to read without the center alignment
- I included a "Contribution" section with two troubleshooting tips. These tips help save time by providing solutions directly, eliminating the need to search through Discord
  - I'm not sure if there is an automated way to handle the second tip involving the two DLLs

### CODE REVIEW

**Comment by V0IDL355** [comment]
I centered everything in the readme cause it looked kind of cursed with some stuff being centered and some not 😅. As for the troubleshooting part, I don't know if the BP is even needed for the C++ but that's more of a Darth thing 😆

**Comment by derpierre65** [comment]
yes, i know what you mean
i removed the center alignment from everything except the shields.io images because they look better that way - perhaps due to the common practice of centering them.
However, centering the entire README.md makes it harder to read, and it's generally uncommon to center the entire README.md.
But i could add it again, the main change is the contribution section (maybe more about that in #105)

**Review by porisius — CHANGES_REQUESTED** [review]
Blueprints are still used, just nowhere nearly as much.

Could you add a link to the CONTRIBUTING.md file, please? I wouldn't know a good place to add it in. Assuming it looks good, I'll merge.

I prefer the left-aligned as well, I just think the IDE I was using to check the last time it was updated didn't note the center-aligned

**Comment by V0IDL355** [comment]
Probably best to uncenter the shield.io stuff too so it doesn't look out of place or smth

**Pull request merged**
