### PR TITLE
Fix #126 - Avoid null dereference on Linux

### LINKED ISSUE #126: GetTrainStation segfault on Linux
As originally [reported by Fezalion on Discord](https://discord.com/channels/1142919853053841488/1142921725269524643/1300183307220156507), a request to `/getTrainStation` with at least one train station built appears to reliably cause a crash on a Linux dedicated server. This is presumably a result of the changes made in 1.1.0 as part of fixing #101.

See the Discord conversation for more details, though when I reproduced this the error I received was as follows.

```
[...]

Unhandled Exception: SIGSEGV: invalid attempt to read memory at address 0x0000000000000010

[2024.10.27-22.19.08:868][159]LogCore: Fatal error!

0x000014d5b252bc51 libFactoryServer-CoreUObject-Linux-Shipping.so!UObjectBase::IsValidLowLevel() const [C:/BuildAgent/work/b731a33f2a691e17/UE4/Engine/Source/./Runtime/CoreUObject/Private/UObject/UObjectBase.cpp:324]
0x000014d53c598ff2 libFactoryServer-FicsitRemoteMonitoring-Linux-Shipping.so!UFRM_Trains::getTrainStation(UObject*) [A:/workspace/SatisfactoryModLoader/Mods/FicsitRemoteMonitoring/Source/FicsitRemoteMonitoring/Private/FRM_Trains.cpp:167]
0x000014d53c5a62dd libFactoryServer-FicsitRemoteMonitoring-Linux-Shipping.so!AFicsitRemoteMonitoring::getTrainStation(UObject*) [A:/workspace/SatisfactoryModLoader/Mods/FicsitRemoteMonitoring/Source/ThirdParty/uWebSockets/../../FicsitRemoteMonitoring/Public/FicsitRemoteMonitoring.h:458]

[...]
```

The steps I used were as follows.

1. Launch a fresh server using [wolveix/satisfactory-server](https://hub.docker.com/r/wolveix/satisfactory-server) on a physical Linux server.
   - Fezalion's logs indicate the game was running under WSL.
2. Install SML+FRM via SMM.
3. Create a new game with most of the advanced game settings enabled.
4. Make a GET to $server:8080/getTrainStation and confirm it returns an empty array.
5. Build a train station. It doesn't need to be connected to anything.
6. Make a GET to $server:8080/getTrainStation. The server crashes immediately, though the client might take a few seconds to realise.

### PR DESCRIPTION
**Pull request by cosmopetrich**
The compiler UE uses for Windows appears to generate code that allows this, whereas clang doesn't.

### CODE REVIEW

**Comment by cosmopetrich** [comment]
Tested on my local machine (Windows) with a save that includes a lot of different train stations and on a Linux dedicated server with a very simple save.

The `IsValidLowLevel` check may not actually be required. I'm not sure scenario could cause the connection to be non-null but also not a valid uobject by whatever tests that method performs, and the code in https://github.com/porisius/FicsitRemoteMonitoring/issues/101#issuecomment-2425647118 which didn't use it seems to work fine. However, there are certainly a lot of things that I don't know about CPP/UE.

**Comment by porisius** [comment]
`IsValidLowLevel` is something I read somewhere, and honestly, it may not be needed. If you want to try it without that, feel free.

Sorry, some of this code is code that "just worked", and I just believed it. Joys/curse of a non-dev.

**Comment by cosmopetrich** [comment]
No need at all need to apologise. I'm definitely not gonna judge given how little I know about SF/UE/etc. I'll test without that check and push another commit if it works.

While digging just then I came across https://forums.unrealengine.com/t/checking-for-null-with-isvalidlowlevel/692232 which notes that IsValid() might be the version intended for end-users like us.

Though I think we can probably assume that if a rail connection is not valid from the engine's perspective then it has probably been disconnected and deleted from the game world first and we wouldn't see get it in the first place barring an unlucky race condition (which we might still hit when calling GetOwner etc anyway).

**Comment by cosmopetrich** [comment]
Updated to remove the IsValidLowLevel test. No crash when run against my save with lots of varied stations, and no crash on Linux. Seems like expected JSON output on both.

**Comment by featheredtoast** [comment]
just FYIU this PR has been opened against `main` - I'm assuming it should target `dev`

**Pull request merged**
